"use client";

import { usePathname } from "next/navigation";
import navMap from "@/lib/page-nav-map.json";

/**
 * PageNav — a small, professional "← Previous | Back to Section | Next →" row.
 *
 * It sits directly below the breadcrumb on content pages. All routing data comes
 * from lib/page-nav-map.json (generated by scripts/build-page-nav-map.js), keyed
 * by pathname. If the current page isn't in the map, this renders nothing — so
 * the Home page, news, and any other unconfigured page are safely unaffected.
 */
type NavEntry = {
  prevHref: string | null;
  nextHref: string | null;
  backHref: string;
  backLabel: string;
};

const MAP = navMap as Record<string, NavEntry>;

export default function PageNav() {
  const pathname = usePathname();

  // Normalise a trailing slash so "/foo/" matches the "/foo" key.
  const key =
    pathname && pathname.length > 1 && pathname.endsWith("/")
      ? pathname.slice(0, -1)
      : pathname;

  const entry = key ? MAP[key] : undefined;
  if (!entry) return null;

  const linkClass =
    "inline-flex items-center gap-1.5 text-sky-800 transition hover:text-red-700";

  return (
    <nav
      aria-label="Page navigation"
      className="mb-6 flex flex-wrap items-center justify-between gap-x-4 gap-y-2 border-y border-slate-200/80 py-2.5 text-xs font-semibold sm:text-sm"
    >
      {entry.prevHref ? (
        <a href={entry.prevHref} className={linkClass}>
          <span aria-hidden="true">←</span> Previous
        </a>
      ) : (
        // Keep "Back to" centred even when there is no previous page.
        <span className="invisible inline-flex items-center gap-1.5" aria-hidden="true">
          <span>←</span> Previous
        </span>
      )}

      <a
        href={entry.backHref}
        className="inline-flex items-center gap-1.5 text-center text-slate-500 transition hover:text-sky-700"
      >
        Back to {entry.backLabel}
      </a>

      {entry.nextHref ? (
        <a href={entry.nextHref} className={linkClass}>
          Next <span aria-hidden="true">→</span>
        </a>
      ) : (
        <span className="invisible inline-flex items-center gap-1.5" aria-hidden="true">
          Next <span>→</span>
        </span>
      )}
    </nav>
  );
}
