"use client";

import type { ProjectData, Defect, OutputType } from "@/lib/scope-builder-types";
import { OUTPUT_TYPE_LABELS } from "@/lib/scope-builder-data";

function renderMarkdown(md: string): string {
  return md
    .replace(
      /^## (.+)$/gm,
      '<h2 class="mt-8 mb-3 text-lg font-extrabold text-sky-950 border-b border-slate-200 pb-2">$1</h2>'
    )
    .replace(
      /^### (.+)$/gm,
      '<h3 class="mt-6 mb-2 text-base font-bold text-sky-950">$1</h3>'
    )
    .replace(
      /^#### (.+)$/gm,
      '<h4 class="mt-4 mb-1 text-sm font-bold text-slate-700">$1</h4>'
    )
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^- (.+)$/gm, '<li class="ml-4 list-disc text-slate-700 leading-6">$1</li>')
    .replace(/(<li[^>]*>[\s\S]*?<\/li>\n?)+/g, (m) => `<ul class="my-2 space-y-0.5">${m}</ul>`)
    .replace(/^\d+\. (.+)$/gm, '<li class="ml-4 list-decimal text-slate-700 leading-6">$1</li>')
    .replace(/^---$/gm, '<hr class="my-6 border-slate-200" />')
    .replace(/^⚠(.+)$/gm, '<div class="my-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">⚠$1</div>')
    .replace(/\n\n/g, '</p><p class="mt-3 text-slate-700 leading-7">')
    .replace(/^(?!<[huldp])(.+)$/gm, '<p class="mt-3 text-slate-700 leading-7">$1</p>');
}

interface Props {
  scope: string;
  project: ProjectData;
  defects: Defect[];
  outputType: OutputType;
}

export function ScopePreview({ scope, project, defects, outputType }: Props) {
  const outputLabel = OUTPUT_TYPE_LABELS[outputType] ?? "Scope of Works";

  const formattedDate = project.reportDate
    ? new Date(project.reportDate).toLocaleDateString("en-AU", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : new Date().toLocaleDateString("en-AU", {
        day: "numeric",
        month: "long",
        year: "numeric",
      });

  return (
    <div className="print-area rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">
      {/* Cover block */}
      <div className="mb-8 border-b border-slate-200 pb-6">
        <div className="text-xs font-extrabold uppercase tracking-[0.25em] text-red-700">
          {outputLabel}
        </div>
        <h2 className="mt-1 text-2xl font-extrabold text-sky-950">
          {project.name || project.address}
        </h2>
        {project.name && (
          <p className="mt-0.5 text-sm text-slate-500">{project.address}</p>
        )}

        <div className="mt-4 grid gap-1.5 text-sm text-slate-600 sm:grid-cols-2">
          {project.clientName && (
            <div>
              <span className="font-semibold text-slate-700">Client:</span>{" "}
              {project.clientName}
            </div>
          )}
          {project.preparedBy && (
            <div>
              <span className="font-semibold text-slate-700">Prepared By:</span>{" "}
              {project.preparedBy}
            </div>
          )}
          <div>
            <span className="font-semibold text-slate-700">Building Type:</span>{" "}
            {project.buildingType}
          </div>
          {project.levels && (
            <div>
              <span className="font-semibold text-slate-700">Levels:</span>{" "}
              {project.levels}
            </div>
          )}
          {project.lots && (
            <div>
              <span className="font-semibold text-slate-700">Lots / Units:</span>{" "}
              {project.lots}
            </div>
          )}
          {project.isClass2 && (
            <div>
              <span className="font-semibold text-slate-700">Class 2:</span> Yes
            </div>
          )}
          {project.coastalExposure && (
            <div>
              <span className="font-semibold text-slate-700">Coastal Exposure:</span> Yes
            </div>
          )}
          <div>
            <span className="font-semibold text-slate-700">Date:</span>{" "}
            {formattedDate}
          </div>
          <div>
            <span className="font-semibold text-slate-700">Format:</span>{" "}
            {outputLabel}
          </div>
        </div>

        {/* Defect tags */}
        {defects.length > 0 && (
          <div className="mt-4 flex flex-wrap gap-2">
            {defects.map((d) => (
              <span
                key={d.id}
                className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600"
              >
                {d.defectType || d.category}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Generated scope content */}
      <div
        className="text-sm"
        dangerouslySetInnerHTML={{ __html: renderMarkdown(scope) }}
      />

      {/* Document footer */}
      <div className="mt-10 border-t border-slate-200 pt-4 text-xs leading-5 text-slate-400">
        Generated by Remedial Building Australia AI Scope Builder ·{" "}
        {new Date().toLocaleDateString("en-AU")}
        <br />
        This document is AI-generated and must be reviewed by a qualified remedial building
        consultant before use. It does not constitute engineering or legal advice.
      </div>
    </div>
  );
}
